### ISSUE TITLE
Documentation, please

### ISSUE THREAD

**Issue by Bluhme1** [zachowj/hass-node-red#3]
I think your integration fills a gap between Hassio and Node Red. Much appreciated.
But I could need som documentation/ explanation how to actually use it. With a few examples

**Comment by zachowj** [comment]
What sort of documentation are you looking for?  Everything you need to know is in the README. Once installed and added via Integrations all configuration is done from Node-RED.

**Comment by Bluhme1** [comment]
I have everything installed ok. But how do I configure the Node Red part? E.g how to create an entity from a node? Perhaps with a few examples  - just like the video in the read me file but with a bit more explaining. A kind of How-to approach

**Comment by zachowj** [comment]
![HDsGU4BCWA](https://user-images.githubusercontent.com/37859597/70994541-552c6980-2083-11ea-8d14-207d273ccb66.gif)

**Comment by Bluhme1** [comment]
Great. So simple. I didn’t have the sensor node until I upgrade through Node Red Palette. Now everything works fine.
Thank you very much

**Comment by vajonam** [comment]
Question about creating a switch to enable/disable flows instead of input_booleans.

0. what is you availability to maintain this project. I have seen custom components fall by the wayside as HA moves on a fast pace. I am considering moving to this method but have some reservations around longevity of this integration, will this be moved into HA long term? (ideal)

1. in the event:state node, I need to always search for "switch.xyz" where 'xyz' is the name specified name field in the expose to HA panel? why aren't the names implied? i.e. it should always be the same right?

**Comment by zachowj** [comment]
@vajonam Actually had to go look, but I have been maintaining [zachowj/node-red-contrib-home-assistant-websocket](https://github.com/zachowj/node-red-contrib-home-assistant-websocket) for over a year now. I don't see a reason why one would continue being maintained and the other wouldn't.

Everyone is going to have their own naming conventions in NR and HA.  The option is there to allow for complete customization.

**Comment by vajonam** [comment]
Question, about poll state, will we see similar behavior for that node? I have a flow that check the state of an input boolean if on one branch, if not other branch, I can simulate this with event: state.. but would more complicated than it is now.

**Comment by vajonam** [comment]
Also another question on the state node, I do not get a "off" even when i turn of the corresponding switch.. what I am missing? it goes into the disabled state but how do I use that to affect a flow?

**Comment by zachowj** [comment]
I think you're interrupting the docs incorrectly.

![image](https://user-images.githubusercontent.com/37859597/71036483-a9ab0580-20d2-11ea-8c39-abb799db69f6.png)

When you expose an event node the switch in HA allow you to enable/disable the node so that the event no longer triggers. It's doesn't trigger the node when you flip the switch in HA. Coming later there will be a service-call where you'll be able to trigger the event node from HA. The same way native automation work in HA.

**Comment by vajonam** [comment]
Yes I understand that. But I guess if I see this an real automation if would make it clear-er. I am not sure what I can do with a disabled node. I cannot stop a flow, cannot change paths to alternate path.. maybe that is what I am missing.

**Comment by vajonam** [comment]
![image](https://user-images.githubusercontent.com/152501/71044418-99f5e600-20ff-11ea-9f32-9cf01db25a3c.png)

I have gotten around by creating 5 switches using the nodes on the left and the on the event: state nodes on the right i control the traffic flow. This determines if the flow progresses.

**Comment by vajonam** [comment]
Lets move this discussion to https://community.home-assistant.io/t/two-new-nodes-with-custom-integration-looking-for-testers/150736/35
