### ISSUE TITLE
Get this into core.

### ISSUE THREAD

**Issue by frenck** [zachowj/hass-node-red#34]
**Is your feature request related to a problem? Please describe.**

Get this custom stuff into the core, and remove the need for users to install this custom component.

**Describe the solution you'd like**

See above

**Describe alternatives you've considered**

Deprecate the Home Assistant Node-RED add-on to get rid of this brain damage I've accumulated over time on users not able to figure this all out.

**Additional context**

No.

**Comment by zachowj** [comment]
If I recall correctly this wouldn't be a component accepted into the core as is communicates directly with an external source using a client-initiated WebSocket connection.

**Comment by frenck** [comment]
Right, so it should become part of the core APIs in that case.

**Comment by zachowj** [comment]
I guess I should have been more clear. Not only does it communicate directly with Node-RED there are also custom sensors and switches that need to exist. So it more than some API endpoints.

**Comment by frenck** [comment]
Those would go into an core integration?


I'm failing to see the issue with that.

In the end, the thing that counts here, is that a lot of users don't have a clue what is going on and what to do.

This confusion caused a lot of frustration with both the end users and as well as me (in terms of support).

Nobody benefits from that confusion. The experience should be made easier and streamlined.

A lot of people without YAML knowledge flee to Node-RED. Yet, now all of a sudden, this happens, HACS, custom integration, add-on?!

We should aim for a single click and go experience.

**Comment by zachowj** [comment]
It is my understanding it would fail acceptance because of [this](https://developers.home-assistant.io/docs/creating_component_code_review#4-communication-with-devicesservices) as it makes direct calls to Node-RED from the HA entities as it using an existing websocket connection initiated from Node-RED.

**Comment by frenck** [comment]
Initiate a separate connection for that?

**Comment by zachowj** [comment]
something change?

**Comment by frenck** [comment]
No.

That is why I closed it.

**Comment by tboothman** [comment]
Is there nothing to be done here?
The 'automation' in home assistant is pretty bewilderingly complicated yet seemly not hugely powerful either.
I, as @frenck mentioned also fell towards node-red as it's powerful, flexbible and easy to use but its turns out it doesn't actually do anything with home assistant entities out of the box.
Downloading files from github into a docker container running on a pi is a bit much for most people. I'm a software engineer and after trying to figure out why node-red wouldn't even start out of the box getting into it and then faced with much more manual intervention I gave up.

I've not looked too much into how this code works but home assistant has an api and a websocket server (which presumably sends value change events) so can't all the connections come from components in node-red to hassio and avoid the code in this repo entirely?
